### ISSUE TITLE
fttb slow response time

### ISSUE THREAD

**Issue by UserZHTW** [flarum/framework#3779] opened 2023-03-30 06:18 UTC
### Current Behavior

我发现了一个BUG，当我的通知数来到5000+，fttb时间会来到2秒以上，但如果我清除了所有通知，则会恢复到400MS
我的母语是中文，担心使用翻译软件会有差异，所以在这里附上中文说明

My native language is Chinese, I am worried that there will be differences when using translation software, so I attach a Chinese explanation here

I found a bug where the fttb (first time to byte) time would exceed 2 seconds when my notification count reached 5000+. However, if I cleared all notifications, the fttb time would return to 400ms.

### Steps to Reproduce

Number of account notifications 5000+

### Expected Behavior

Slow initial server response time

### Environment

- Flarum version: 1.7.2
- Webserver: nginx
- Hosting environment: dedicated server
- PHP version: 8.1.7
- Browser: Chrome

### Output of `php flarum info`

![https://i.imgur.com/2AGPXZol.jpg](https://i.imgur.com/2AGPXZol.jpg)

**Comment by davwheat** [comment] 2023-03-30 08:53
Duplicate of #3778

**Closed as not planned** 2023-03-30 08:53 UTC
Labels: type/bug
